version: 1
disable_existing_loggers: false
formatters:
    simple:
        format: '%(asctime)s [%(levelname)7s] [%(name)s] [%(filename)s:%(lineno)s|%(module)s.%(funcName)s] %(message)s'
loggers:
    all:
        handlers: [console]
        propagate: false
    tornado:
        handlers: [console]
        propagate: false
    program:
        handlers: [console]
        propagate: false
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    tornado:
        class: logging.handlers.TimedRotatingFileHandler
        level: INFO
        formatter: simple
        when: midnight
        backupCount: 30
        filename: logs/tornado.log
    program:
        class: logging.handlers.TimedRotatingFileHandler
        level: INFO
        formatter: simple
        when: midnight
        backupCount: 30
        filename: logs/server.log
root:
    level: INFO
    handlers: [console]
    propagate: true